version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"

  postgres:
    image: "postgres:15.1"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data